### ISSUE TITLE
Slayer OHS Too many resets 

### ISSUE THREAD

**Issue by andersonepk** [caali-hackerman/skill-resets#2]
The icon remains for 4 seg then disapear.
So when the first OHS is reset it work fine, but then if i use again while icon still on in screen, the mod not show if reseted again.

A easy fix would be change the time of the icon remain on screen, 
there is someplace that i can edit to it?
if not, would be wonderfull if u could fix it somehow.
Thanks for the mod.
gl

**Comment by SaltyMonkey** [comment]
fixed
